--[=[
-- C_AreaPoiInfo API Documentation
-- Generated from warcraft.wiki.gg
-- Generated on: 2025-08-02 23:23:19
-- Functions: 8
--]=]

--- @class C_AreaPoiInfo
--- C_AreaPoiInfo namespace contains 8 functions
local C_AreaPoiInfo = {}

--[=[
-- C_AreaPoiInfo Functions:
-- - C_AreaPoiInfo.GetAreaPOIForMap
-- - C_AreaPoiInfo.GetAreaPOIInfo
-- - C_AreaPoiInfo.GetAreaPOISecondsLeft
-- - C_AreaPoiInfo.GetDelvesForMap
-- - C_AreaPoiInfo.GetDragonridingRacesForMap
-- - C_AreaPoiInfo.GetEventsForMap
-- - C_AreaPoiInfo.GetQuestHubsForMap
-- - C_AreaPoiInfo.IsAreaPOITimed
--]=]

---======================================================================
--- C_AreaPoiInfo.GetAreaPOIForMap
---======================================================================
--- Returns area points of interest for a map.
---
--- Arguments:
--- @param uiMapID number : UiMapID
---
--- Returns:
--- @return number areaPoiIDs [] : AreaPOI
---
--- @since Patch 8.0.1 (2018-07-17): Added.
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetAreaPOIForMap
---
--- Usage: areaPoiIDs = C_AreaPoiInfo.GetAreaPOIForMap(uiMapID)
---
-- function C_AreaPoiInfo.GetAreaPOIForMap()
-- end

---======================================================================
--- C_AreaPoiInfo.GetAreaPOIInfo
---======================================================================
--- Returns info for an area point of interest (e.g. World PvP objectives).
---
--- Arguments:
--- @param uiMapID number ? : UiMapID - When omitted this appears to default to the relevant ui map id, regardless of the player's current location or any ui map being viewed.
--- @param areaPoiID number : AreaPOI
---
--- Returns:
--- @return AreaPOIInfo poiInfo
---
--- @since Patch 11.1.0 (2025-02-25): uiMapID argument is optional.
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetAreaPOIInfo
---
--- Usage: poiInfo = C_AreaPoiInfo.GetAreaPOIInfo([uiMapID], areaPoiID)
---
-- function C_AreaPoiInfo.GetAreaPOIInfo()
-- end

---======================================================================
--- C_AreaPoiInfo.GetAreaPOISecondsLeft
---======================================================================
--- Returns the time left in seconds for an area point of interest.
---
--- Arguments:
--- @param areaPoiID number - area point of interest ID.
---
--- Returns:
--- @return number secondsLeft - time left in seconds.
---
--- @since Patch 8.1.5 (2019-03-12): Replaces C_AreaPoiInfo.GetAreaPOITimeLeft()[1]
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetAreaPOISecondsLeft
---
--- Usage: secondsLeft = C_AreaPoiInfo.GetAreaPOISecondsLeft(areaPoiID)
---
-- function C_AreaPoiInfo.GetAreaPOISecondsLeft()
-- end

---======================================================================
--- C_AreaPoiInfo.GetDelvesForMap
---======================================================================
--- Returns all area POIInfos flagged as delves for the given map.
---
--- Arguments:
--- @param uiMapID number
---
--- Returns:
--- @return number areaPoiIDs []
---
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetDelvesForMap
---
--- Usage: areaPoiIDs = C_AreaPoiInfo.GetDelvesForMap(uiMapID)
---
-- function C_AreaPoiInfo.GetDelvesForMap()
-- end

---======================================================================
--- C_AreaPoiInfo.GetDragonridingRacesForMap
---======================================================================
--- Returns all area POIInfos flagged as dragonriding races for the given map.
---
--- Arguments:
--- @param uiMapID number
---
--- Returns:
--- @return number areaPoiIDs []
---
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetDragonridingRacesForMap
---
--- Usage: areaPoiIDs = C_AreaPoiInfo.GetDragonridingRacesForMap(uiMapID)
---
-- function C_AreaPoiInfo.GetDragonridingRacesForMap()
-- end

---======================================================================
--- C_AreaPoiInfo.IsAreaPOITimed
---======================================================================
--- Returns whether an area poi is timed.
---
--- Arguments:
--- @param areaPoiID number
---
--- Returns:
--- @return boolean isTimed
--- @return boolean hideTimerInTooltip ?
---
--- @since Patch 10.1.0 (2023-05-02): Added hideTimerInTooltip return.
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.IsAreaPOITimed
---
--- Usage: isTimed, hideTimerInTooltip = C_AreaPoiInfo.IsAreaPOITimed(areaPoiID)
---
-- function C_AreaPoiInfo.IsAreaPOITimed()
-- end

---======================================================================
--- C_AreaPoiInfo.GetEventsForMap
---======================================================================
--- Returns all area POIInfos flagged as events for the given map.
---
--- Arguments:
--- @param uiMapID number
---
--- Returns:
--- @return number areaPoiIDs []
---
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetEventsForMap
---
--- Usage: areaPoiIDs = C_AreaPoiInfo.GetEventsForMap(uiMapID)
---
-- function C_AreaPoiInfo.GetEventsForMap()
-- end

---======================================================================
--- C_AreaPoiInfo.GetQuestHubsForMap
---======================================================================
--- Returns all area POIInfos flagged as quest hubs for the given map.
---
--- Arguments:
--- @param uiMapID number
---
--- Returns:
--- @return number areaPoiIDs []
---
--- @see https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetQuestHubsForMap
---
--- Usage: areaPoiIDs = C_AreaPoiInfo.GetQuestHubsForMap(uiMapID)
---
-- function C_AreaPoiInfo.GetQuestHubsForMap()
-- end
